# Generated by Django 4.2.20 on 2025-04-02 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="Products",
        ),
    ]
