# Generated by Django 4.2.20 on 2025-04-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_products_category_orders"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="product",
        ),
        migrations.AddField(
            model_name="orders",
            name="product",
            field=models.ManyToManyField(related_name="orders", to="products.products"),
        ),
    ]
